In [2]:
import tensorflow as tf
mnist = tf.keras.datasets.mnist

In [3]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [4]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [5]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.12399256, -0.19056594, -0.28015637, -0.26217645, -0.9409102 ,
        -0.6793218 , -0.03642699, -0.17565064,  0.41503227,  0.44032136]],
      dtype=float32)

In [7]:
tf.nn.softmax(predictions).numpy()

array([[0.09812224, 0.0918026 , 0.08393563, 0.08545843, 0.04334955,
        0.05631071, 0.10710178, 0.09318212, 0.1682143 , 0.17252254]],
      dtype=float32)

In [8]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [9]:
loss_fn(y_train[:1], predictions).numpy()


2.8768706

In [10]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [11]:
model.fit(x_train, y_train, epochs=5)


Epoch 1/5
1875/1875 [==============================] - 2s 715us/step - loss: 0.2951 - accuracy: 0.9134
Epoch 2/5
1875/1875 [==============================] - 1s 727us/step - loss: 0.1442 - accuracy: 0.9563
Epoch 3/5
1875/1875 [==============================] - 1s 695us/step - loss: 0.1097 - accuracy: 0.9668
Epoch 4/5
1875/1875 [==============================] - 1s 721us/step - loss: 0.0871 - accuracy: 0.9726
Epoch 5/5
1875/1875 [==============================] - 1s 678us/step - loss: 0.0748 - accuracy: 0.9772


In [12]:
model.evaluate(x_test,  y_test, verbose=2)


313/313 - 0s - loss: 0.0748 - accuracy: 0.9768


[0.07480458170175552, 0.9768000245094299]

In [13]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [14]:
probability_model(x_test[:5])


<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[3.9231089e-09, 6.1744687e-10, 1.2808099e-06, 2.5270650e-05,
        7.3152847e-12, 3.6819792e-08, 5.6414559e-14, 9.9997044e-01,
        2.1515650e-07, 2.7700582e-06],
       [5.7722339e-08, 4.9324040e-05, 9.9943942e-01, 3.8994665e-04,
        3.0552861e-14, 6.4226037e-07, 5.9415882e-08, 5.3067485e-12,
        1.2070264e-04, 9.3052072e-14],
       [3.7604750e-08, 9.9965537e-01, 8.5253523e-05, 4.5803818e-06,
        2.2943401e-05, 9.0067950e-08, 3.1231111e-06, 1.8457152e-04,
        4.3963635e-05, 1.3290251e-07],
       [9.9918860e-01, 2.9904637e-09, 5.0100201e-04, 1.6705218e-07,
        3.8899534e-06, 1.0332901e-04, 1.2725446e-05, 1.3488003e-05,
        3.0102245e-07, 1.7646443e-04],
       [3.7840934e-07, 1.8987112e-08, 1.4290646e-05, 7.4567104e-08,
        9.8618537e-01, 1.2199895e-06, 9.0609582e-08, 2.1694017e-04,
        2.1822857e-06, 1.3579584e-02]], dtype=float32)>